'use client';
import {useEffect,useState} from 'react';
import {categories,sources} from '../lib/sources';
export default function Home(){
 const [category,setCategory]=useState('all');const [query,setQuery]=useState('');const [saved,setSaved]=useState<string[]>([]);const [onlySaved,setOnlySaved]=useState(false);const [dark,setDark]=useState(false);const [storageReady,setStorageReady]=useState(false);const [note,setNote]=useState('');
 useEffect(()=>{try{const value=JSON.parse(localStorage.getItem('langbaan-saved')||'[]');if(Array.isArray(value))setSaved(value.filter((v):v is string=>typeof v==='string'));setDark(localStorage.getItem('langbaan-theme')==='dark')}catch{setNote('ไม่สามารถอ่านรายการที่บันทึกไว้ได้')}setStorageReady(true)},[]);
 useEffect(()=>{if(storageReady)try{localStorage.setItem('langbaan-saved',JSON.stringify(saved));localStorage.setItem('langbaan-theme',dark?'dark':'light')}catch{setNote('เบราว์เซอร์ไม่อนุญาตให้บันทึกข้อมูล รายการจะเก็บไว้เฉพาะครั้งนี้')}},[saved,dark,storageReady]);
 const filtered=sources.filter(s=>(category==='all'||s.category===category)&&(!onlySaved||saved.includes(s.id))&&(`${s.name} ${s.host} ${categories.find(c=>c.id===s.category)?.name}`.toLowerCase().includes(query.toLowerCase().trim())));
 return <div className={dark?'site dark':'site'}><header><a className="brand" href="/" aria-label="Langbaan Invest หน้าแรก"><span className="brand-icon">↗</span><span>LANGBAAN <b>INVEST</b><small>อ่านตลาด เข้าใจการลงทุน</small></span></a><nav><button className={!onlySaved?'active':''} onClick={()=>setOnlySaved(false)}>แหล่งข่าว</button><button className={onlySaved?'active':''} onClick={()=>setOnlySaved(true)}>ที่บันทึกไว้ <span>{saved.length}</span></button><button className="theme" onClick={()=>setDark(!dark)} aria-label={dark?'ใช้โหมดสว่าง':'ใช้โหมดมืด'}>{dark?'☀':'☾'}</button></nav></header>
 <main><section className="hero"><div className="hero-copy"><div className="eyebrow"><span/> YOUR INVESTMENT READING ROOM</div><h1>มองตลาดให้กว้างขึ้น<br/><em>เข้าใจการลงทุนให้ลึกกว่าเดิม</em></h1><p>ข่าวรายวัน มุมมองจากสถาบันการเงิน และข้อมูลต้นทาง<br className="desktop"/> รวมแหล่งอ้างอิงที่คุณเลือกไว้ ในพื้นที่เดียว</p><a className="cta" href="#directory">สำรวจแหล่งอ้างอิง <span>↗</span></a></div><div className="hero-art" aria-hidden="true"><div className="art-label">THE BIG PICTURE <span>↗</span></div><div className="chart"><i/><i/><i/><i/><i/><i/><i/><i/></div><div className="art-bottom"><span>READ. UNDERSTAND. INVEST.</span><b>ข้อมูลก่อนการตัดสินใจ</b></div></div></section>
 <section className="stats" aria-label="ภาพรวมแหล่งอ้างอิง"><div><strong>{sources.length}</strong><span>แหล่งอ้างอิงที่คัดเลือก</span></div><div><strong>7</strong><span>หมวดหมู่การลงทุน</span></div><div><strong>A–G</strong><span>จากข่าวถึงข้อมูลต้นทาง</span></div><p>รู้ที่มา อ่านต้นฉบับ<br/><b>สร้างมุมมองของคุณเอง</b></p></section>
 <section id="directory" className="directory"><div className="section-top"><div><div className="eyebrow">SOURCE DIRECTORY</div><h2>{onlySaved?'แหล่งอ้างอิงที่บันทึกไว้':'ห้องอ่านข่าวการลงทุน'}</h2><p>ลิงก์ไปยังเว็บไซต์ต้นทาง • ยังไม่ได้ดึงข่าวสดหรือยืนยันการเข้าถึง</p></div><label className="search"><span aria-hidden="true">⌕</span><input aria-label="ค้นหาแหล่งอ้างอิง" placeholder="ค้นหาชื่อ แหล่งข่าว หรือหัวข้อ..." value={query} onChange={e=>setQuery(e.target.value)}/>{query&&<button onClick={()=>setQuery('')} aria-label="ล้างการค้นหา">×</button>}</label></div>
 <div className="workspace"><aside><div className="aside-title">เลือกหมวดหมู่</div><button className={category==='all'?'selected':''} onClick={()=>setCategory('all')}><span className="category-letter">▦</span><span>ทั้งหมด</span><small>{sources.length}</small></button>{categories.map(c=><button key={c.id} className={category===c.id?'selected':''} onClick={()=>setCategory(c.id)}><span className="category-letter">{c.id}</span><span>{c.name}</span><small>{sources.filter(s=>s.category===c.id).length}</small></button>)}<div className="aside-note"><b>เริ่มจากข้อมูลต้นทาง</b><p>เปรียบเทียบหลายแหล่ง และตรวจวันที่เผยแพร่ก่อนนำข้อมูลไปใช้</p></div></aside><div className="results"><div className="result-heading"><h3>{category==='all'?'ทุกแหล่งอ้างอิง':categories.find(c=>c.id===category)?.name}</h3><span aria-live="polite">{filtered.length} รายการ</span></div>{note&&<p role="status">{note}</p>}<div className="cards">{filtered.map(s=><article className="card" key={s.id}><div className="card-top"><span className={'badge badge-'+s.category}>{s.category} · {categories.find(c=>c.id===s.category)?.name}</span><button className={'bookmark '+(saved.includes(s.id)?'is-saved':'')} aria-label={`${saved.includes(s.id)?'เลิกบันทึก':'บันทึก'} ${s.name}`} aria-pressed={saved.includes(s.id)} onClick={()=>setSaved(prev=>prev.includes(s.id)?prev.filter(id=>id!==s.id):[...prev,s.id])}>{saved.includes(s.id)?'★':'☆'}</button></div><h4><a href={s.url} target="_blank" rel="noopener noreferrer">{s.name}</a></h4><p>{categories.find(c=>c.id===s.category)?.description}</p><div className="card-footer"><span>{s.host}</span><a href={s.url} target="_blank" rel="noopener noreferrer" aria-label={`อ่านต้นทาง ${s.name} เปิดแท็บใหม่`}>อ่านต้นทาง ↗</a></div>{s.category==='G'&&<small className="access-note">ต้องตรวจการเข้าถึงก่อนใช้งาน</small>}</article>)}</div>{filtered.length===0&&<div className="empty"><span>⌕</span><h3>{onlySaved&&!saved.length?'ยังไม่มีแหล่งอ้างอิงที่บันทึก':'ไม่พบรายการที่ตรงกับการค้นหา'}</h3><p>กด ☆ บนแหล่งที่สนใจ หรือเปลี่ยนคำค้นและหมวดหมู่</p><button onClick={()=>{setQuery('');setCategory('all');setOnlySaved(false)}}>ดูแหล่งอ้างอิงทั้งหมด</button></div>}{(category==='F'||category==='all')&&<div className="ir-note"><span>F</span><div><b>Investor Relations ของบริษัท</b><p>เพิ่ม URL ทางการตาม watchlist ภายหลัง โดยตรวจสอบว่าเป็นเว็บไซต์ของบริษัทจริงก่อนเพิ่ม</p></div></div>}</div></div></section>
 <section className="reading-guide"><div className="eyebrow">A BETTER READING HABIT</div><h2>อ่านข่าวอย่างมีบริบท</h2><div><p><b>01 / ติดตามความเคลื่อนไหว</b><span>เริ่มจากข่าวรายวันในหมวด A</span></p><p><b>02 / เติมมุมมอง</b><span>เปรียบเทียบบทวิเคราะห์ในหมวด B และ C</span></p><p><b>03 / ตรวจสอบต้นทาง</b><span>ใช้ข้อมูลและเอกสารในหมวด D–F</span></p></div></section></main><footer><a className="footer-brand" href="/">LANGBAAN <b>INVEST ↗</b></a><p>พื้นที่รวบรวมแหล่งอ้างอิงการลงทุน • ข้อมูลเพื่อการศึกษา</p><small>บางเว็บไซต์อาจต้องสมัครสมาชิกหรือมีข้อจำกัดในการเข้าถึง<br/>รายการที่บันทึกไว้เก็บในเบราว์เซอร์นี้</small></footer></div>
}
