'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import type {DailyArticle} from '../lib/daily-news';
import {topics} from '../lib/news-topics';
import AssetLinks from './AssetLinks';
type DailyNews={articles:DailyArticle[];retrievedAt:string;fallback:boolean;snapshotAt:string};
export default function DailyReader(){const [news,setNews]=useState<DailyNews|null>(null);const [error,setError]=useState(false);const [query,setQuery]=useState('');const [topic,setTopic]=useState('all');
useEffect(()=>{const c=new AbortController();fetch('/api/daily-news',{signal:c.signal}).then(r=>{if(!r.ok)throw Error();return r.json()}).then(setNews).catch(()=>{if(!c.signal.aborted)setError(true)});return()=>c.abort()},[]);
const items=news?.articles.filter(a=>(topic==='all'||a.topic===topic)&&`${a.title} ${a.content} ${a.mentionedSymbols.join(' ')} ${topics[a.topic]}`.toLowerCase().includes(query.toLowerCase().trim()))||[];
return <section id="daily-news" className="news-section"><div className="section-top"><div><div className="eyebrow">DAILY NEWS WATCH</div><h2>ติดตามข่าวและประกาศล่าสุด</h2><p>ฟีดประกาศทางการจาก Fed • ตรวจทุก 15 นาทีเมื่อมีการเข้าใช้งาน<br/>เผยแพร่ตามวันที่มีประกาศ ไม่ได้มีข่าวใหม่ทุกวัน • ยังไม่ใช่ฟีดข่าวตลาดจากสำนักข่าว</p></div><label className="search"><input placeholder="ค้นหาข่าว บริษัท หรือสินทรัพย์..." aria-label="ค้นหาข่าวล่าสุด" value={query} onChange={e=>setQuery(e.target.value)}/></label></div><div className="news-filters"><button aria-pressed={topic==='all'} onClick={()=>setTopic('all')}>ทั้งหมด</button>{['FED_MONETARY','FED_BANKING','FED_OTHER'].map(t=><button key={t} aria-pressed={topic===t} onClick={()=>setTopic(t)}>{topics[t]}</button>)}</div>{error&&<p role="alert">โหลดข่าวไม่สำเร็จ กรุณาลองรีโหลดหน้าเว็บ</p>}{!news&&!error&&<p role="status">กำลังโหลดข่าว…</p>}{news&&<><p className="news-status">{news.fallback?`ใช้ข้อมูลสำรองที่เก็บเมื่อ ${new Date(news.snapshotAt).toLocaleString('th-TH',{timeZone:'Asia/Shanghai'})}`:`ตรวจฟีดเมื่อ ${new Date(news.retrievedAt).toLocaleString('th-TH',{timeZone:'Asia/Shanghai'})}`} (UTC+8) • เนื้อหาอังกฤษ ยังไม่มีคำแปลไทย</p><div className="cards daily-cards">{items.slice(0,12).map(a=><article className="card" key={a.id}><span className="badge badge-D">Fed · {topics[a.topic]}</span><h4 lang="en"><Link href={`/news/${a.id}`}>{a.title}</Link></h4>{a.content!==a.title&&<p lang="en">{a.content}</p>}{a.mentionedSymbols.length>0&&<div className="direct-mentions"><small>บริษัทที่กล่าวถึงโดยตรง</small><div className="asset-chips">{a.mentionedSymbols.map(s=><Link key={s} href={`/assets/${s}`}>{s} ↗</Link>)}</div></div>}<AssetLinks topic={a.topic}/><div className="card-footer"><span>{new Date(a.published).toLocaleDateString('th-TH',{timeZone:'Asia/Shanghai'})}</span><Link href={`/news/${a.id}`}>อ่านประกาศย่อ →</Link></div></article>)}</div>{!items.length&&<p className="empty">ไม่พบข่าวที่ตรงกับการค้นหา</p>}</>}<p className="news-license">แหล่งที่มา: Board of Governors of the Federal Reserve System • ใช้เฉพาะข้อความประกาศที่เป็นสาธารณสมบัติ ไม่ใช้ภาพหรือตราหน่วยงาน • <a href="https://www.federalreserve.gov/disclaimer.htm" target="_blank" rel="noopener noreferrer">เงื่อนไขการใช้เนื้อหา ↗</a></p></section>
}
