'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import type {Article} from '../lib/news';
const labels:Record<string,string>={CPI:'เงินเฟ้อผู้บริโภค (CPI)',EMPLOYMENT:'การจ้างงานสหรัฐฯ',PPI:'ราคาผู้ผลิต (PPI)'};
type News={articles:Article[];retrievedAt:string;fallbackTopics:string[];snapshotAt:string};
export default function NewsReader(){const [news,setNews]=useState<News|null>(null);const [error,setError]=useState(false);const [topic,setTopic]=useState('all');const [search,setSearch]=useState('');const [language,setLanguage]=useState<'th'|'en'>('th');
 useEffect(()=>{const c=new AbortController();fetch('/api/news',{signal:c.signal}).then(r=>{if(!r.ok)throw Error();return r.json()}).then(setNews).catch(()=>{if(!c.signal.aborted)setError(true)});return()=>c.abort()},[]);
 const items=news?.articles.filter(a=>(topic==='all'||a.topic===topic)&&(`${a.title} ${a.content} ${a.translation?.title||''} ${a.translation?.content||''} ${labels[a.topic]}`.toLowerCase().includes(search.trim().toLowerCase())))||[];
 return <section className="news-section" id="news"><div className="section-top"><div><div className="eyebrow">OFFICIAL ECONOMIC RELEASES</div><h2>อ่านประกาศเศรษฐกิจในเว็บเรา</h2><p>ประกาศย่อจาก BLS พร้อมคำแปลภาษาไทย • อ่านต้นฉบับอังกฤษเทียบได้</p></div><label className="search"><input aria-label="ค้นหาประกาศเศรษฐกิจ" placeholder="ค้นหาประกาศหรือหัวข้อ..." value={search} onChange={e=>setSearch(e.target.value)}/></label></div><div className="language-switch" role="group" aria-label="เลือกภาษาข่าว"><button aria-pressed={language==='th'} onClick={()=>setLanguage('th')}>ภาษาไทย</button><button aria-pressed={language==='en'} onClick={()=>setLanguage('en')}>English</button></div><div className="news-filters"><button onClick={()=>setTopic('all')} aria-pressed={topic==='all'}>ทั้งหมด</button>{Object.entries(labels).map(([id,label])=><button key={id} onClick={()=>setTopic(id)} aria-pressed={topic===id}>{label}</button>)}</div>
 {!news&&!error&&<p role="status">กำลังโหลดประกาศจากแหล่งข้อมูล…</p>}{error&&<p role="alert">โหลดประกาศไม่สำเร็จ กรุณาลองรีโหลดหน้าเว็บ</p>}
 {news&&<><p className="news-status" role="status">{news.fallbackTopics.length?`บางฟีดเชื่อมต่อไม่ได้ ใช้ข้อมูลสำรองสำหรับ ${news.fallbackTopics.map(t=>labels[t]).join(', ')} ที่เก็บเมื่อ ${new Date(news.snapshotAt).toLocaleString('th-TH',{timeZone:'Asia/Shanghai'})}`:`ตรวจสอบฟีดเมื่อ ${new Date(news.retrievedAt).toLocaleString('th-TH',{timeZone:'Asia/Shanghai'})} • ระบบตรวจใหม่ทุกชั่วโมงเมื่อมีการเข้าใช้งาน`} • เวลาแสดง UTC+8</p><div className="cards news-cards">{items.slice(0,12).map(a=><article className="card" key={a.id}><span className="badge">BLS · {labels[a.topic]}</span><h4><Link href={`/news/${encodeURIComponent(a.id)}`}>{language==='th'&&a.translation?a.translation.title:a.title}</Link></h4><p lang={language==='th'&&a.translation?'th':'en'}>{language==='th'&&a.translation?a.translation.content:a.content}</p>{language==='th'&&<small className="translation-note">{a.translation?'คำแปลโดย AI ของ Langbaan Invest • ไม่ใช่คำแปลทางการ':'ยังไม่มีคำแปลสำหรับเนื้อหาฉบับนี้ แสดงต้นฉบับอังกฤษ'}</small>}<div className="card-footer"><span>{new Date(a.published).toLocaleDateString('th-TH',{timeZone:'Asia/Shanghai'})}</span><Link href={`/news/${encodeURIComponent(a.id)}`}>อ่านในเว็บเรา →</Link></div></article>)}</div>{!items.length&&<p className="empty">ไม่พบประกาศที่ตรงกับคำค้นหรือหมวดที่เลือก</p>}</>}
 <p className="news-license">อ้างอิง U.S. Bureau of Labor Statistics ใช้เฉพาะข้อความสาธารณสมบัติ ไม่ใช้ตราหน่วยงานหรือภาพประกอบที่มีลิขสิทธิ์ • <a href="https://www.bls.gov/bls/linksite.htm" target="_blank" rel="noopener noreferrer">เงื่อนไขการใช้เนื้อหา ↗</a></p></section>
}
