export const categories = [
 {id:'A',name:'ข่าวรายวัน',description:'ติดตามความเคลื่อนไหวของตลาดและข่าวที่ต้องรู้'},
 {id:'B',name:'มุมมองและกลยุทธ์ลงทุน',description:'มองภาพใหญ่ผ่านบทวิเคราะห์จากสถาบันการเงิน'},
 {id:'C',name:'กำไรบริษัทและมูลค่าตลาด',description:'อ่านผลประกอบการและทำความเข้าใจมูลค่าหุ้น'},
 {id:'D',name:'ข้อมูลเศรษฐกิจและธนาคารกลาง',description:'ข้อมูลต้นทางสำหรับเงินเฟ้อ ดอกเบี้ย และเศรษฐกิจ'},
 {id:'E',name:'เศรษฐกิจโลก',description:'แนวโน้มและข้อมูลเศรษฐกิจระหว่างประเทศ'},
 {id:'F',name:'เอกสารบริษัท',description:'ค้นหาเอกสารที่บริษัทยื่นต่อหน่วยงานกำกับ'},
 {id:'G',name:'แหล่งเสริม',description:'กราฟและข้อมูลเพิ่มเติม • ต้องตรวจการเข้าถึง'},
];
const rows: [string,string,string][] = [
['A','Seeking Alpha — Market News','https://seekingalpha.com/market-news'],
['A','Yahoo Finance','https://finance.yahoo.com/'],
['A','Yahoo Finance — Stock Market News','https://finance.yahoo.com/topic/stock-market-news/'],
['A','Investing.com — Latest News','https://www.investing.com/news/latest-news'],
['A','Investing.com — Stock Market News','https://www.investing.com/news/stock-market-news'],
['A','CNBC — Markets','https://www.cnbc.com/markets/'],
['A','CNBC — US Market','https://www.cnbc.com/us-market/'],
['B','J.P. Morgan — Weekly Market Recap','https://am.jpmorgan.com/us/en/asset-management/adv/insights/market-insights/market-updates/weekly-market-recap/'],
['B','BlackRock — Weekly Commentary','https://www.blackrock.com/corporate/insights/blackrock-investment-institute/global-weekly-commentary'],
['B','Morgan Stanley — Insights','https://www.morganstanley.com/insights'],
['B','Morgan Stanley — Thoughts on the Market','https://www.morganstanley.com/insights/podcasts/thoughts-on-the-market'],
['B','Charles Schwab — Market Commentary','https://www.schwab.com/learn/market-commentary'],
['B','Vanguard — Market Perspectives','https://advisors.vanguard.com/insights/article/series/market-perspectives'],
['B','Fidelity — Viewpoints','https://www.fidelity.com/learning-center/viewpoints'],
['B','PIMCO — Insights','https://www.pimco.com/us/en/insights'],
['B','State Street Investment Management — Market Trends','https://www.ssga.com/us/en/intermediary/insights/market-trends'],
['B','State Street — Research & Insights','https://www.statestreet.com/us/en/solutions/research-and-insights'],
['C','FactSet — Earnings Insight','https://www.factset.com/earningsinsight'],
['C','FactSet — Insight','https://insight.factset.com/'],
['C','J.P. Morgan — Guide to the Markets','https://am.jpmorgan.com/us/en/asset-management/adv/insights/market-insights/guide-to-the-markets/'],
['D','FRED — Economic Data','https://fred.stlouisfed.org/'],
['D','FRED — Economic Releases','https://fred.stlouisfed.org/releases'],
['D','BLS — CPI','https://www.bls.gov/cpi/'],
['D','BLS — CPI Latest Release','https://www.bls.gov/news.release/cpi.htm'],
['D','BEA','https://www.bea.gov/'],
['D','Federal Reserve — FOMC Calendars and Documents','https://www.federalreserve.gov/monetarypolicy/fomccalendars.htm'],
['D','Federal Reserve — News and Events','https://www.federalreserve.gov/newsevents.htm'],
['D','New York Fed — Data and Indicators','https://www.newyorkfed.org/research/data_indicators/'],
['D','New York Fed — Global Supply Chain Pressure Index','https://www.newyorkfed.org/research/policy/gscpi'],
['E','IMF — Data','https://www.imf.org/en/data'],
['E','IMF — World Economic Outlook','https://www.imf.org/en/publications/weo'],
['E','OECD — Economic Outlook','https://www.oecd.org/en/topics/sub-issues/economic-outlook.html'],
['F','SEC — Search Filings','https://www.sec.gov/search-filings'],
['F','SEC — Full Text Search','https://www.sec.gov/edgar/search/'],
['G','Yardeni — Stock Market P/E Ratios','https://yardeni.com/charts/us-stock-market/stock-market-valuation/stock-market-p-e-ratios'],
['G','Yardeni — Charts','https://yardeni.com/charts'],
];
export const sources = rows.map(([category,name,url],id)=>({id:String(id),category,name,url,host:new URL(url).hostname.replace(/^www\./,'')}));
